# Generated by Django 3.0.7 on 2021-01-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
